kind: pipeline
type: docker
name: default
steps:

  - name: build
    image: plugins/docker
    settings:
      repo: andrewmclagan/drone-gcloud
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password      
      tags: 
        - latest
        - ${DRONE_TAG=${DRONE_COMMIT}}
